version: "3"
services:
  ms-feedbacksettings-sandbox:
    container_name: ms-feedbacksettings-sandbox
    image: 'ms-feedbacksettings:sandbox'
    links:
      - 'ms-feedbacksettings-db-sandbox:mariadb'
    restart: always
    build:
      context: ../../..
      dockerfile: ./src/main/docker/Dockerfile
    ports:
      - "8704:8080"
    environment:
      SPRING_PROFILES_ACTIVE: 'sandbox'
      SPRING_JPA_PROPERTIES_JAVAX_PERSISTENCE_SCHEMA_GENERATION_DATABASE_ACTION: 'update'
      SPRING_DATASOURCE_URL: 'jdbc:mariadb://mariadb:3306/sandbox-feedbacksettings'
      SPRING_DATASOURCE_USERNAME: 'sandbox-user'
      SPRING_DATASOURCE_PASSWORD: 'sandbox-password'
    depends_on:
      - ms-feedbacksettings-db-sandbox

  ms-feedbacksettings-db-sandbox:
    container_name: ms-feedbacksettings-db-sandbox
    image: 'mariadb:10.6.4'
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD : 'yes'
      MARIADB_DATABASE: 'sandbox-feedbacksettings'
      MARIADB_USER: 'sandbox-user'
      MARIADB_PASSWORD: 'sandbox-password'
    expose:
      - '3306'